name: Update GitHub Pages every hour

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour at minute 0

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run Python script
        run: python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically updated index.html"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: ShockPlease <ShockPlease@users.noreply.github.com>
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          create_branch: false
          internal_git_binary: git
          repository: .
          file_pattern: .
          skip_cleanup: true
          push_to: "origin"
          access_token: ${{ secrets.shock_token }}
